package personDBTable;

import java.awt.event.WindowEvent;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neil Otupacca
 * @version 27 November 2021
 */
public class PersonDBFrame extends JFrame {

    // Costanti per gli indice delle 4 colonne della JTable.
    private static final int FIRSTNAME_TABLE_COLUMN = 0;
    private static final int LASTNAME_TABLE_COLUMN = 1;
    private static final int EMAIL_TABLE_COLUMN = 2;
    private static final int ADDRESS_TABLE_COLUMN = 3;

    private Connection conn;

    /**
     * Creates new form PersonDBFrame
     */
    public PersonDBFrame() {
        initComponents();

        // Listener per l'evento del cambio di selezione nella JTable.
        ListSelectionModel selectionModel = this.personDataTable.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // L'utente ha selezionato una nuova item della JTable.
                // Dalla documentazione di Java:
                // Returns whether or not this is one in a series of multiple
                // events, where changes are still being made.
                // See the documentation for
                //   ListSelectionModel.setValueIsAdjusting(boolean)
                // for more details on how this is used.
                // Returns: true if this is one in a series of multiple events,
                //          where changes are still being made.
                if (e.getValueIsAdjusting()) {
                    return;
                }

                // Aggiorna lo stato della GUI.
                updateGUI();

                // Ottieni l'indice della row selezionata nella JTable (-1 se
                // nessuna selezione è attiva).
                int selRow = personDataTable.getSelectedRow();
                if (selRow < 0) {
                    return;
                }

                // Ottieni il DefaultTableModel della JTable.
                // Nota: a differenza delle ultime 3 colonne (che contengono
                //       direttamente le stringhe di 'lastname', 'email' e
                //       'address'), la prima colonna (firstname) contiene un
                //       oggetto di tipo IdFirstnameItem, questo include la
                //       stringa per il 'firstname' e l'id della corrispondente
                //       row nel DB (la PK).
                //       L'id deve essere memorizzato (serve per le queries), ma
                //       non visualizzato (PK surrogata), vedi metodo toString()
                //       della classe IdFirstnameItem che, dei due dati, mostra
                //       appunto solo il 'firstname'.
                DefaultTableModel dtm = (DefaultTableModel) personDataTable.getModel();

                // Una selezione è attiva nella JTable, copia i dati della row
                // selezionata nei relativi JTextFiels.
                IdFirstnameItem firstnameItem = (IdFirstnameItem) dtm.getValueAt(selRow,
                        PersonDBFrame.FIRSTNAME_TABLE_COLUMN);

                // Il 'firstname' è estratto dall'oggetto firstnameItem, gli
                // altri dati sono estratti direttamente dalle celle come stringhe.
                firstnameTextField.setText(firstnameItem.getFirstname());
                lastnameTextField.setText((String) dtm.getValueAt(selRow, PersonDBFrame.LASTNAME_TABLE_COLUMN));
                emailTextField.setText((String) dtm.getValueAt(selRow, PersonDBFrame.EMAIL_TABLE_COLUMN));
                addressTextField.setText((String) dtm.getValueAt(selRow, PersonDBFrame.ADDRESS_TABLE_COLUMN));
            }
        });

        // Crea o apri il database.
        this.createOrOpenDB();

        // Popola la JTable.
        this.refreshTableContent();

        // Inizializza lo stato della GUI.
        this.updateGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        personTableScrollPane = new javax.swing.JScrollPane();
        personDataTable = new javax.swing.JTable();
        firstnameLabel = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        lastnameTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        descRadioButton = new javax.swing.JRadioButton();
        ascRadioButton = new javax.swing.JRadioButton();
        orderButton = new javax.swing.JButton();
        orderComboBox = new javax.swing.JComboBox<>();
        capLabel1 = new javax.swing.JLabel();
        capTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Person List");
        setMinimumSize(new java.awt.Dimension(580, 300));

        personDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Firstname", "Lastname", "E-mail", "Address"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        personDataTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        personDataTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        personTableScrollPane.setViewportView(personDataTable);

        firstnameLabel.setText("Firstname");
        firstnameLabel.setMaximumSize(new java.awt.Dimension(50, 14));
        firstnameLabel.setMinimumSize(new java.awt.Dimension(50, 14));
        firstnameLabel.setPreferredSize(new java.awt.Dimension(50, 14));

        firstnameTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                textFieldsChangedKeyReleased(evt);
            }
        });

        lastnameLabel.setText("Lastname");
        lastnameLabel.setMaximumSize(new java.awt.Dimension(52, 14));
        lastnameLabel.setMinimumSize(new java.awt.Dimension(52, 14));
        lastnameLabel.setPreferredSize(new java.awt.Dimension(52, 14));

        lastnameTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                textFieldsChangedKeyReleased(evt);
            }
        });

        emailLabel.setText("E-mail");
        emailLabel.setMaximumSize(new java.awt.Dimension(50, 14));
        emailLabel.setMinimumSize(new java.awt.Dimension(50, 14));
        emailLabel.setPreferredSize(new java.awt.Dimension(50, 14));

        emailTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                textFieldsChangedKeyReleased(evt);
            }
        });

        addressLabel.setText("Address");
        addressLabel.setMaximumSize(new java.awt.Dimension(52, 14));
        addressLabel.setMinimumSize(new java.awt.Dimension(52, 14));
        addressLabel.setPreferredSize(new java.awt.Dimension(52, 14));

        addressTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                textFieldsChangedKeyReleased(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.setToolTipText("Update the Person list content");
        refreshButton.setPreferredSize(new java.awt.Dimension(86, 23));
        refreshButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                refreshButtonActionPerformed(evt);
            }
        });

        insertButton.setText("Insert");
        insertButton.setToolTipText("Insert a new Person in the Database");
        insertButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.setToolTipText("Update the data of selected Person");
        updateButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.setToolTipText("Delete the selected Person");
        deleteButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Order by");

        buttonGroup1.add(descRadioButton);
        descRadioButton.setText("DESC");

        buttonGroup1.add(ascRadioButton);
        ascRadioButton.setText("ASC");

        orderButton.setText("Ordina");
        orderButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                orderButtonActionPerformed(evt);
            }
        });

        orderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Firstname", "Lastname", "Email", "Address", "CAP" }));

        capLabel1.setText("CAP");
        capLabel1.setMaximumSize(new java.awt.Dimension(52, 14));
        capLabel1.setMinimumSize(new java.awt.Dimension(52, 14));
        capLabel1.setPreferredSize(new java.awt.Dimension(52, 14));

        capTextField1.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                capTextField1textFieldsChangedKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(emailTextField))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastnameTextField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(capLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(capTextField1)
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ascRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(descRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(personTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(capLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(capTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(firstnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateButton)
                        .addComponent(lastnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertButton)
                    .addComponent(deleteButton)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descRadioButton)
                    .addComponent(ascRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // Aggiorna il contenuto della JTable con il contenuto del DB.
        this.refreshTableContent();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // Inserisci una nuova row nel database.
        String sql = "INSERT INTO person (firstname, lastname, email, address)"
                + " VALUES(?, ?, ?, ?)";
        try ( PreparedStatement pstmt = this.conn.prepareStatement(sql)) {
            // Sostituisci i quattro place-holder con i valori stringa dei
            // relativi JTextField.
            pstmt.setString(1, this.firstnameTextField.getText());
            pstmt.setString(2, this.lastnameTextField.getText());
            pstmt.setString(3, this.emailTextField.getText());
            pstmt.setString(4, this.addressTextField.getText());

            // Esegui la query di INSERT.
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Person List",
                    JOptionPane.ERROR_MESSAGE);
        }

        // Aggiorna il contenuto della JTable (con i nuovi dati del DB).
        this.refreshTableContent();
    }//GEN-LAST:event_insertButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // Ottieni l'id (PK) della row nel database, questo è incapsulato
        // nell'oggetto IdFirstnameItem della prima colonna della row selezionata
        // nella JTable (-1 se nessuna selezione è attiva).
        // Id della row selezionata nella JTable.
        int selRow = this.personDataTable.getSelectedRow();
        if (selRow < 0) {
            return;
        }

        // Ritorna l'oggetto IdFirstnameItem (nella prima colonna).
        DefaultTableModel dtm = (DefaultTableModel) this.personDataTable.getModel();
        IdFirstnameItem idItem = (IdFirstnameItem) dtm.getValueAt(selRow,
                PersonDBFrame.FIRSTNAME_TABLE_COLUMN);

        // Modifica la row del DB (identificata dalla PK) corrispondente alla
        // row attualmente selezionata nella JTable.
        String sql = "UPDATE person SET firstname = ?, lastname = ?,"
                + " email = ?, address = ?"
                + " WHERE id = ?";
        try ( PreparedStatement pstmt = this.conn.prepareStatement(sql)) {
            // Modifica 'firstname', 'lastname', 'email' e 'address' (nel
            // database) con i valori stringa dei relativi JTextField.
            pstmt.setString(1, this.firstnameTextField.getText());
            pstmt.setString(2, this.lastnameTextField.getText());
            pstmt.setString(3, this.emailTextField.getText());
            pstmt.setString(4, this.addressTextField.getText());
            pstmt.setInt(5, idItem.getId());  // PK per la clusola WHERE.

            // Esegui la query di UPDATE.
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Person List",
                    JOptionPane.ERROR_MESSAGE);
        }

        // Aggiorna il contenuto della JTable (con i nuovi dati del DB).
        this.refreshTableContent();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // Ottieni l'id (PK) della row nel database, questo è incapsulato
        // nell'oggetto IdFirstnameItem della prima colonna della row selezionata
        // nella JTable (-1 se nessuna selezione è attiva).
        // Id della row selezionata nella JTable.
        int selRow = this.personDataTable.getSelectedRow();
        if (selRow < 0) {
            return;
        }

        // Ritorna l'oggetto IdFirstnameItem (nella prima colonna).
        DefaultTableModel dtm = (DefaultTableModel) this.personDataTable.getModel();
        IdFirstnameItem idItem = (IdFirstnameItem) dtm.getValueAt(selRow,
                PersonDBFrame.FIRSTNAME_TABLE_COLUMN);

        // Elimina una row del DB (identificata dalla PK) corrispondente alla
        // row attualmente selezionata nella JTable.
        String sql = "DELETE FROM person WHERE id = ?";
        try ( PreparedStatement pstmt = this.conn.prepareStatement(sql)) {
            // Imposta la condizione della clausola WHERE con il valore dell'id
            // incapsulato nell'oggetto IdFirstnameItem.
            pstmt.setInt(1, idItem.getId());  // PK per la clusola WHERE.

            // Esegui la query DELETE.
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Person List",
                    JOptionPane.ERROR_MESSAGE);
        }

        // Aggiorna il contenuto della JTable (con i nuovi dati del DB).
        this.refreshTableContent();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void textFieldsChangedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldsChangedKeyReleased
        // Aggiorna lo stato della GUI.
        this.updateGUI();
    }//GEN-LAST:event_textFieldsChangedKeyReleased

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        // Order by.
         // Ottieni il DefaultTableModel della JTable ed elimina tutte le row
        // della JTable (verranno sostituite dai nuovi dati nel DB).
        DefaultTableModel dtm = (DefaultTableModel) this.personDataTable.getModel();
        dtm.setRowCount(0);

        try ( Statement stmt = this.conn.createStatement()) {
            // Esegui la SELECT e inserisci le row del DB nella JTable.
            String comboBox = this.orderComboBox.getSelectedItem().toString();
            System.out.println(comboBox);
            String query = "SELECT * FROM person ORDER BY " + comboBox + " ";
            query += (this.ascRadioButton.isSelected()) ? "ASC" : "DESC";
            System.out.println(query);
            try ( ResultSet rs = stmt.executeQuery(query)) {
                // Itera il resultSet.
                while (rs.next()) {
                    // Imposta l'array di Object con i dati della row da inserire.
                    // Un elemento Object può essere impostato direttamente con
                    // qualsiasi tipo di dato, questa operazione si chiama "boxing".
                    // L
                    Object[] rowData = {
                        new IdFirstnameItem(rs.getInt("id"),
                        rs.getString("firstname")),
                        rs.getString("lastname"),
                        rs.getString("email"),
                        rs.getString("address")
                    };

                    // Inserisci la nuova row.
                    dtm.addRow(rowData);
                }
            }

            // Aggiorna lo stato della GUI, dato che la JTable è stata svuotata
            // e poi ripopolata, una sua eventuale row-selection è andata persa.
            this.updateGUI();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Person List",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_orderButtonActionPerformed

    private void capTextField1textFieldsChangedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_capTextField1textFieldsChangedKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_capTextField1textFieldsChangedKeyReleased

    private void refreshTableContent() {
        // Ottieni il DefaultTableModel della JTable ed elimina tutte le row
        // della JTable (verranno sostituite dai nuovi dati nel DB).
        DefaultTableModel dtm = (DefaultTableModel) this.personDataTable.getModel();
        dtm.setRowCount(0);

        try ( Statement stmt = this.conn.createStatement()) {
            // Esegui la SELECT e inserisci le row del DB nella JTable.
            String sql = "SELECT * FROM person ORDER BY lastname, firstname";
            try ( ResultSet rs = stmt.executeQuery(sql)) {
                // Itera il resultSet.
                while (rs.next()) {
                    // Imposta l'array di Object con i dati della row da inserire.
                    // Un elemento Object può essere impostato direttamente con
                    // qualsiasi tipo di dato, questa operazione si chiama "boxing".
                    // L
                    Object[] rowData = {
                        new IdFirstnameItem(rs.getInt("id"),
                        rs.getString("firstname")),
                        rs.getString("lastname"),
                        rs.getString("email"),
                        rs.getString("address")
                    };

                    // Inserisci la nuova row.
                    dtm.addRow(rowData);
                }
            }

            // Aggiorna lo stato della GUI, dato che la JTable è stata svuotata
            // e poi ripopolata, una sua eventuale row-selection è andata persa.
            this.updateGUI();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Person List",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

//    private void orderBy() {
//        // Ottieni il DefaultTableModel della JTable ed elimina tutte le row
//        // della JTable (verranno sostituite dai nuovi dati nel DB).
//        DefaultTableModel dtm = (DefaultTableModel) this.personDataTable.getModel();
//        dtm.setRowCount(0);
//
//        try ( Statement stmt = this.conn.createStatement()) {
//            // Esegui la SELECT e inserisci le row del DB nella JTable.
//            String comboBox = this.orderComboBox.getSelectedItem().toString();
//            System.out.println(comboBox);
//            String query = "SELECT * FROM person ORDER BY " + comboBox + " ";
//            query += (this.ascRadioButton.isSelected()) ? "ASC" : "DESC";
//            System.out.println(query);
//            try ( ResultSet rs = stmt.executeQuery(query)) {
//                // Itera il resultSet.
//                while (rs.next()) {
//                    // Imposta l'array di Object con i dati della row da inserire.
//                    // Un elemento Object può essere impostato direttamente con
//                    // qualsiasi tipo di dato, questa operazione si chiama "boxing".
//                    // L
//                    Object[] rowData = {
//                        new IdFirstnameItem(rs.getInt("id"),
//                        rs.getString("firstname")),
//                        rs.getString("lastname"),
//                        rs.getString("email"),
//                        rs.getString("address")
//                    };
//
//                    // Inserisci la nuova row.
//                    dtm.addRow(rowData);
//                }
//            }
//
//            // Aggiorna lo stato della GUI, dato che la JTable è stata svuotata
//            // e poi ripopolata, una sua eventuale row-selection è andata persa.
//            this.updateGUI();
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, ex.getMessage(),
//                    "Person List",
//                    JOptionPane.ERROR_MESSAGE);
//        }
//    }

    private void updateGUI() {
        // Determina lo stato dei 3 JTextField e se la JTable ha una selezione.
        boolean isValidData = !this.firstnameTextField.getText().isBlank()
                && !this.lastnameTextField.getText().isBlank()
                && !this.emailTextField.getText().isBlank()
                && !this.addressTextField.getText().isBlank();
        boolean hasSelection = this.personDataTable.getSelectedRow() >= 0;

        // Aggiorna lo stato di 'enabled' dei button.
        this.insertButton.setEnabled(isValidData);
        this.updateButton.setEnabled(isValidData && hasSelection);
        this.deleteButton.setEnabled(hasSelection);
    }

    private void createOrOpenDB() {
        try {
            Class.forName("org.sqlite.JDBC");

            // Apre la connessione con il database, se il db non esiste, viene creato.
            this.conn = DriverManager.getConnection("jdbc:sqlite:Person.db");

            // Crea la tabella 'person' se non esiste ancora.
            try ( Statement stmt = this.conn.createStatement()) {
                String sql = "CREATE TABLE IF NOT EXISTS person ("
                        + " id INTEGER NOT NULL,"
                        + " firstname TEXT NOT NULL,"
                        + " lastname  TEXT NOT NULL,"
                        + " email TEXT NOT NULL,"
                        + " address  TEXT NOT NULL,"
                        + " PRIMARY KEY (id))";
                stmt.executeUpdate(sql);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            String err = ex.getMessage().trim();
            if (ex instanceof ClassNotFoundException) {
                err = "Class '" + err + "' not found.";
            }

            JOptionPane.showMessageDialog(null,
                    err + "\n\nTerminating the application!",
                    "Person List",
                    JOptionPane.ERROR_MESSAGE);

            // Termina l'applicazione, errore non rimediabile.
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PersonDBFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JRadioButton ascRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel capLabel1;
    private javax.swing.JTextField capTextField1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JRadioButton descRadioButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JButton orderButton;
    private javax.swing.JComboBox<String> orderComboBox;
    private javax.swing.JTable personDataTable;
    private javax.swing.JScrollPane personTableScrollPane;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
