package toDoManagerDBTable;

import java.awt.Dimension;
import java.awt.event.WindowEvent;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 * DB per lista todo
 *
 * @date 05.12.2022
 * @author tommasoernestom.zani
 */
public class ToDoDBFrame extends javax.swing.JFrame {
    // Costanti per gli indice delle 4 colonne della JTable.

    private static final int TITLE_TABLE_COLUMN = 0;
    private static final int DESCRIPTION_TABLE_COLUMN = 1;
    private static final int DEADLINE_TABLE_COLUMN = 2;

    private Connection conn;

    /**
     * Creates new form ToDoDBFrame
     */
    public ToDoDBFrame() {
        initComponents();
        setMinimumSize(new Dimension(900, 500));
        setLocation(500, 250);

        ListSelectionModel selectionModel = this.toDoTable.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                if (e.getValueIsAdjusting()) {
                    return;
                }
                updateGUI();
                
                int selRow = toDoTable.getSelectedRow();
                if (selRow < 0) {
                    return;
                }
                DefaultTableModel dtm = (DefaultTableModel) toDoTable.getModel();
                descriptionTextField.setText((String) dtm.getValueAt(selRow, ToDoDBFrame.TITLE_TABLE_COLUMN));
                descriptionTextField.setText((String) dtm.getValueAt(selRow, ToDoDBFrame.DESCRIPTION_TABLE_COLUMN));
                deadlineTextField.setText((String) dtm.getValueAt(selRow, ToDoDBFrame.DEADLINE_TABLE_COLUMN));
            }
        });

        this.createOrOpenDB();

        this.refreshTableContent();

        this.updateGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toDoScrollPane = new javax.swing.JScrollPane();
        toDoTable = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        deadlineTextField = new javax.swing.JTextField();
        deadlineLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        deleteAllButton = new javax.swing.JButton();
        sortByLabel = new javax.swing.JLabel();
        sortByComboBox = new javax.swing.JComboBox<>();
        reloadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toDoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Description", "Deadline"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        toDoTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        toDoScrollPane.setViewportView(toDoTable);

        titleLabel.setText("Title:");

        titleTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                titleTextFieldKeyReleased(evt);
            }
        });

        descriptionLabel.setText("Description:");

        descriptionTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descriptionTextFieldKeyReleased(evt);
            }
        });

        deadlineTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                deadlineTextFieldKeyReleased(evt);
            }
        });

        deadlineLabel.setText("Deadline:");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        deleteAllButton.setText("Delete All");
        deleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllButtonActionPerformed(evt);
            }
        });

        sortByLabel.setText("Sort by:");
        sortByLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        sortByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title ▼", "Title ▲", "Description ▼", "Description ▲", "Deadline ▼", "Deadline ▲" }));

        reloadButton.setText("Reload");
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toDoScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(deadlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(descriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                            .addComponent(titleTextField)
                            .addComponent(deadlineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(deleteAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sortByComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sortByLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toDoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sortByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sortByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(reloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titleLabel)
                        .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionLabel)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deadlineLabel)
                    .addComponent(deadlineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String sql = "INSERT INTO todo (title, description, deadline)"
                + " VALUES(?, ?, ?)";
        try (PreparedStatement pstmt = this.conn.prepareStatement(sql)) {

            pstmt.setString(1, this.titleTextField.getText());
            pstmt.setString(2, this.descriptionTextField.getText());
            pstmt.setString(3, this.deadlineTextField.getText());

            pstmt.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Person List",
                    JOptionPane.ERROR_MESSAGE);
        }
        this.refreshTableContent();
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selRow = this.toDoTable.getSelectedRow();
        if (selRow < 0) {
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) this.toDoTable.getModel();
        String sql = "DELETE FROM todo WHERE title = ?";
        try (PreparedStatement pstmt = this.conn.prepareStatement(sql)) {
            pstmt.setObject(1, dtm.getValueAt(selRow, TITLE_TABLE_COLUMN));
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "todo List",
                    JOptionPane.ERROR_MESSAGE);
        }
        this.refreshTableContent();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void deleteAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllButtonActionPerformed
        int selRow = this.toDoTable.getSelectedRow();
        if (selRow < 0) {
            return;
        }

        DefaultTableModel dtm = (DefaultTableModel) this.toDoTable.getModel();
        String sql = "TRUNCATE TABLE todo";
        try (PreparedStatement pstmt = this.conn.prepareStatement(sql)) {

            pstmt.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "todo List",
                    JOptionPane.ERROR_MESSAGE);
        }

        this.refreshTableContent();
    }//GEN-LAST:event_deleteAllButtonActionPerformed

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) this.toDoTable.getModel();
        dtm.setRowCount(0);
        String comboBox = this.sortByComboBox.getSelectedItem().toString();

        if (comboBox == "Title ▼") {
            try (Statement stmt = this.conn.createStatement()) {
                String query = "SELECT * FROM todo ORDER BY title desc";
                try (ResultSet rs = stmt.executeQuery(query)) {
                    while (rs.next()) {
                        String[] rowData = {
                            rs.getString("title"),
                            rs.getString("description"),
                            rs.getString("deadline")
                        };
                        dtm.addRow(rowData);
                    }
                }
                this.updateGUI();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),
                        "Todo List",
                        JOptionPane.ERROR_MESSAGE);
            };
        } else if (comboBox == "Title ▲") {
            try (Statement stmt = this.conn.createStatement()) {
                String query = "SELECT * FROM todo ORDER BY title asc";
                try (ResultSet rs = stmt.executeQuery(query)) {
                    while (rs.next()) {
                        String[] rowData = {
                            rs.getString("title"),
                            rs.getString("description"),
                            rs.getString("deadline")
                        };
                        dtm.addRow(rowData);
                    }
                }
                this.updateGUI();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),
                        "Todo List",
                        JOptionPane.ERROR_MESSAGE);
            };
        } else if (comboBox == "Description ▼") {
            try (Statement stmt = this.conn.createStatement()) {

                String query = "SELECT * FROM todo ORDER BY description desc";

                try (ResultSet rs = stmt.executeQuery(query)) {
                    while (rs.next()) {
                        String[] rowData = {
                            rs.getString("title"),
                            rs.getString("description"),
                            rs.getString("deadline")
                        };
                        dtm.addRow(rowData);
                    }
                }
                this.updateGUI();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),
                        "Todo List",
                        JOptionPane.ERROR_MESSAGE);
            };
        } else if (comboBox == "Description ▲") {
            try (Statement stmt = this.conn.createStatement()) {
                String query = "SELECT * FROM todo ORDER BY description asc";
                try (ResultSet rs = stmt.executeQuery(query)) {
                    while (rs.next()) {
                        String[] rowData = {
                            rs.getString("title"),
                            rs.getString("description"),
                            rs.getString("deadline")
                        };
                        dtm.addRow(rowData);
                    }
                }
                this.updateGUI();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),
                        "Todo List",
                        JOptionPane.ERROR_MESSAGE);
            };
        } else if (comboBox == "Deadline ▼") {
            try (Statement stmt = this.conn.createStatement()) {
                String query = "SELECT * FROM todo ORDER BY deadline desc";
                try (ResultSet rs = stmt.executeQuery(query)) {
                    while (rs.next()) {
                        String[] rowData = {
                            rs.getString("title"),
                            rs.getString("description"),
                            rs.getString("deadline")
                        };
                        dtm.addRow(rowData);
                    }
                }
                this.updateGUI();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),
                        "Todo List",
                        JOptionPane.ERROR_MESSAGE);
            };
        } else {
            try (Statement stmt = this.conn.createStatement()) {
                String query = "SELECT * FROM todo ORDER BY deadline asc";
                try (ResultSet rs = stmt.executeQuery(query)) {
                    while (rs.next()) {
                        String[] rowData = {
                            rs.getString("title"),
                            rs.getString("description"),
                            rs.getString("deadline")
                        };
                        dtm.addRow(rowData);
                    }
                }
                this.updateGUI();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(),
                        "Todo List",
                        JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_reloadButtonActionPerformed

    private void titleTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleTextFieldKeyReleased
        this.updateGUI();
    }//GEN-LAST:event_titleTextFieldKeyReleased

    private void descriptionTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptionTextFieldKeyReleased
        this.updateGUI();
    }//GEN-LAST:event_descriptionTextFieldKeyReleased

    private void deadlineTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deadlineTextFieldKeyReleased
        this.updateGUI();
    }//GEN-LAST:event_deadlineTextFieldKeyReleased

    private void refreshTableContent() {
        DefaultTableModel dtm = (DefaultTableModel) this.toDoTable.getModel();
        dtm.setRowCount(0);

        try (Statement stmt = this.conn.createStatement()) {
            String sql = "SELECT * FROM todo ORDER BY title, description";
            try (ResultSet rs = stmt.executeQuery(sql)) {
                while (rs.next()) {

                    String[] rowData = {
                        rs.getString("title"),
                        rs.getString("description"),
                        rs.getString("deadline")
                    };

                    dtm.addRow(rowData);
                }
            }

            this.updateGUI();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Todo List",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateGUI() {
        boolean isValidData = !this.titleTextField.getText().isBlank()
                && !this.descriptionTextField.getText().isBlank()
                && !this.deadlineTextField.getText().isBlank();
        boolean hasSelection = this.toDoTable.getSelectedRow() >= 0;

        this.addButton.setEnabled(isValidData);
        this.deleteButton.setEnabled(hasSelection);
        this.deleteButton.setEnabled(hasSelection);
    }

    private void createOrOpenDB() {
        try {
            Class.forName("org.sqlite.JDBC");

            this.conn = DriverManager.getConnection("jdbc:sqlite:ToDo.db");
            
                       
            try (Statement stmt = this.conn.createStatement()) {
                String sql = "CREATE TABLE IF NOT EXISTS todo ("
                        + " title TEXT NOT NULL,"
                        + " description TEXT NOT NULL,"
                        + " deadline TEXT NOT NULL,"
                        + " PRIMARY KEY (title))";
                stmt.executeUpdate(sql);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            String err = ex.getMessage().trim();
            if (ex instanceof ClassNotFoundException) {
                err = "Class '" + err + "' not found.";
            }

            JOptionPane.showMessageDialog(null,
                    err + "\n\nTerminating the application!",
                    "Todo List",
                    JOptionPane.ERROR_MESSAGE);

            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToDoDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToDoDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToDoDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToDoDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToDoDBFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel deadlineLabel;
    private javax.swing.JTextField deadlineTextField;
    private javax.swing.JButton deleteAllButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JButton reloadButton;
    private javax.swing.JComboBox<String> sortByComboBox;
    private javax.swing.JLabel sortByLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JScrollPane toDoScrollPane;
    private javax.swing.JTable toDoTable;
    // End of variables declaration//GEN-END:variables
}
