package personDB;

import java.awt.EventQueue;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.awt.Dimension;
import java.awt.Rectangle;

/**
 *
 * @author Neil Otupacca
 */
public class PersonDBFrame extends JFrame {

    private Connection conn;
    private final int constHeight;

    /**
     * Creates new form PersonDBFrame
     */
    public PersonDBFrame() {
        this.initComponents();

        // Crea o apri il database.
        this.createOrOpenDB();

        // Determina l'altezza corrente del frame.
        // Nota: il metodo setMaximumSize() non funziona (bug JDK-6383434),
        //       l'intenzione è quella di mantenere un'altezza fissa e di
        //       permettere solo il ridimensionmento della larghezza del JFrame.
        this.constHeight = this.getHeight();
        this.setMinimumSize(new Dimension(300, constHeight));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, constHeight));
        this.setMaximizedBounds(new Rectangle(0, 0, this.getWidth(), constHeight));
        this.setSize(this.getWidth(), constHeight);

        // Inizializza il ComboBox con i nomi e cognomi correntemente nel DB.
        // Nota: il precedente contenuto del comboBox viene sostituito.
        this.fullNameComboBox.setModel(new DefaultComboBoxModel(this.getFullNames()));

        // Inizializza lo stato dei button.
        this.updateGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullNameComboLabel = new javax.swing.JLabel();
        fullNameComboBox = new javax.swing.JComboBox();
        groupBoxPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista Persone");

        fullNameComboLabel.setText("Persona:");

        fullNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameComboBoxActionPerformed(evt);
            }
        });

        groupBoxPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dettagli  Persona"));

        firstNameLabel.setText("Nome:");
        firstNameLabel.setToolTipText("");

        firstNameTextField.setToolTipText("");
        firstNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                personDetailsKeyReleased(evt);
            }
        });

        lastNameLabel.setText("Cognome:");

        lastNameTextField.setToolTipText("");
        lastNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                personDetailsKeyReleased(evt);
            }
        });

        insertButton.setText("Inserisci");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Modifica");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Elimina");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout groupBoxPanelLayout = new javax.swing.GroupLayout(groupBoxPanel);
        groupBoxPanel.setLayout(groupBoxPanelLayout);
        groupBoxPanelLayout.setHorizontalGroup(
            groupBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupBoxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groupBoxPanelLayout.createSequentialGroup()
                        .addComponent(insertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addGap(0, 109, Short.MAX_VALUE))
                    .addGroup(groupBoxPanelLayout.createSequentialGroup()
                        .addGroup(groupBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(lastNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(groupBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameTextField)
                            .addComponent(lastNameTextField))))
                .addContainerGap())
        );
        groupBoxPanelLayout.setVerticalGroup(
            groupBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupBoxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(groupBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel))
                .addGap(18, 18, 18)
                .addGroup(groupBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fullNameComboLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fullNameComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(groupBoxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameComboLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(groupBoxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fullNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameComboBoxActionPerformed
        // Aggiorna il form con nome e cognome della persona correntemente
        // selezionata nel ComboBox.
        String sql = "SELECT * FROM person WHERE firstname = ? AND lastname = ?";
        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            // Imposta la condizione della clausola WHERE con i valori di
            // 'firstname' e 'lastName' della selezione corrente del comboBox.
            ComboItem ci = (ComboItem) this.fullNameComboBox.getSelectedItem();
            pstmt.setString(1, ci.getFirstname());
            pstmt.setString(2, ci.getLastname());

            // Esegui la SELECT e imposta i JTextField con nome e cognome della
            // persona selezionata.
            try (ResultSet rs = pstmt.executeQuery()) {
                // Utilizza lo statement 'if' anziché 'while', ci interessa
                // solo la prima row (se esiste).
                // Nota: la SELECT ritorna una row oppure zero row.
                if (rs.next()) {
                    // Estrai i valori stringa (row corrente) delle colonne
                    // 'firstname' e 'lastname' e assegnali ai relativi JTextField.
                    this.firstNameTextField.setText(rs.getString("firstname"));
                    this.lastNameTextField.setText(rs.getString("lastname"));
                }
            }

            // Aggiorna lo stato dei button se la selezione del comboBox è cambiata.
            this.updateGUI();
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                                          "Lista Persone",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_fullNameComboBoxActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // Inserisci una nuova row nel database.
        String sql = "INSERT INTO person (firstname, lastname) VALUES(?, ?)";
        try (PreparedStatement pstmt = this.conn.prepareStatement(sql)) {
            // Sostituisci i due place-holder dei nuovi dati con i valori
            // stringa dei relativi JTextField.
            String fn = this.firstNameTextField.getText();
            String ln = this.lastNameTextField.getText();
            pstmt.setString(1, fn);
            pstmt.setString(2, ln);

            // Esegui la query, aggiorna il contenuto del ComboBox (con il nuovo
            // contenuto del database) e seleziona la item del comboBox appena
            // inserta.
            pstmt.executeUpdate();
            this.fullNameComboBox.setModel(new DefaultComboBoxModel(this.getFullNames()));
            this.fullNameComboBox.setSelectedItem(new ComboItem(fn, ln));
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                                          "Lista Persone",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_insertButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // Modifica una row del database.
        String sql = "UPDATE person SET firstname = ?, lastname = ?" +
                     " WHERE firstname = ? AND lastname = ?";
        try (PreparedStatement pstmt = this.conn.prepareStatement(sql)) {
            // Modifica 'firstname' e 'lastname' (nel database) con i valori
            // stringa dei relativi JTextField.
            String fn = this.firstNameTextField.getText();
            String ln = this.lastNameTextField.getText();
            pstmt.setString(1, fn);
            pstmt.setString(2, ln);

            // Imposta la condizione della clausola WHERE con i valori di
            // 'firstname' e 'lastName' della selezione corrente del comboBox.
            // Nota: la selezione corrente del comboBox contiene ancora i valori
            //       di 'firstname' e 'lastname' precedenti alla modifica.
            ComboItem ci = (ComboItem) this.fullNameComboBox.getSelectedItem();
            pstmt.setString(3, ci.getFirstname());
            pstmt.setString(4, ci.getLastname());

            // Esegui la query, aggiorna il contenuto del ComboBox (con il nuovo
            // contenuto del database) e seleziona la item del comboBox appena
            // modificata.
            pstmt.executeUpdate();
            this.fullNameComboBox.setModel(new DefaultComboBoxModel(this.getFullNames()));
            this.fullNameComboBox.setSelectedItem(new ComboItem(fn, ln));
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                                          "Lista Persone",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // Elimina una row del database.
        String sql = "DELETE FROM person WHERE firstname = ? AND lastname = ?";
        try (PreparedStatement pstmt = this.conn.prepareStatement(sql)) {
            // Imposta la condizione della clausola WHERE con i valori di
            // 'firstname' e 'lastName' della selezione corrente del comboBox.
            ComboItem ci = (ComboItem) this.fullNameComboBox.getSelectedItem();
            pstmt.setString(1, this.firstNameTextField.getText());
            pstmt.setString(2, this.lastNameTextField.getText());

            // Esegui la query e aggiorna il contenuto del ComboBox con il nuovo
            // contenuto del database.
            pstmt.executeUpdate();
            this.fullNameComboBox.setModel(new DefaultComboBoxModel(this.getFullNames()));
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                                          "Lista Persone",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void personDetailsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personDetailsKeyReleased
        // Aggiorna lo stato dei button se l'utente ha digitato nel campo
        // 'firstname' o 'lastname'.
        this.updateGUI();
    }//GEN-LAST:event_personDetailsKeyReleased

    private void updateGUI() {
        // Determina lo stato dei due JTextField e se il comboBox ha una selezione.
        boolean isValidData = !this.firstNameTextField.getText().isBlank() &&
                              !this.lastNameTextField.getText().isBlank();
        boolean hasSelection = this.fullNameComboBox.getSelectedIndex() >= 0;

        // Aggiorna lo stato di 'enabled' dei button.
        this.insertButton.setEnabled(isValidData);
        this.updateButton.setEnabled(isValidData && hasSelection);
        this.deleteButton.setEnabled(hasSelection);
    }

    private void createOrOpenDB() {
        try {
            Class.forName("org.sqlite.JDBC");

            // Apre la connessione con il database, se il db non esiste, viene creato.
            this.conn = DriverManager.getConnection("jdbc:sqlite:Person.db");

            // Crea la tabella 'person' se non esiste ancora.
            try (Statement stmt = this.conn.createStatement()) {
                String sql = "CREATE TABLE IF NOT EXISTS person (" +
                             " firstname TEXT NOT NULL," +
                             " lastname  TEXT NOT NULL," +
                             " PRIMARY KEY (firstname, lastname))";
                stmt.executeUpdate(sql);
            }
        }
        catch (ClassNotFoundException | SQLException ex) {
            String err = ex.getMessage().trim();
            if (ex instanceof ClassNotFoundException) {
                err = "Class '" + err + "' not found.";
            }

            JOptionPane.showMessageDialog(null, err + "\n\nTermina l'applicazione!",
                                          "Lista Persone",
                                          JOptionPane.ERROR_MESSAGE);

            // Termina l'applicazione.
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }

    @SuppressWarnings("CollectionsToArray")
    private ComboItem[] getFullNames() {
        // Ritorna la lista dei nomi e cognomi.
        ArrayList<ComboItem> fullNameList = new ArrayList();

        try (Statement stmt = this.conn.createStatement()) {
            String sql = "SELECT firstname, lastname" +
                         " FROM person ORDER BY lastname, firstname";

            try (ResultSet rs = stmt.executeQuery(sql)) {
                while(rs.next()) {
                    fullNameList.add(new ComboItem(rs.getString("firstname"),
                                                   rs.getString("lastname")));
                }
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                                          "Lista Persone",
                                          JOptionPane.ERROR_MESSAGE);
        }

        return fullNameList.toArray(new ComboItem[fullNameList.size()]);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Look & feel di sistema.
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException |
                 IllegalAccessException | UnsupportedLookAndFeelException ex) {
        }

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PersonDBFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JComboBox fullNameComboBox;
    private javax.swing.JLabel fullNameComboLabel;
    private javax.swing.JPanel groupBoxPanel;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
