package jtableMultiDataColumn;

import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neil Otupacca
 * @version 21 November 2022
 */
public class JTableJFrame extends javax.swing.JFrame {

    private static final int ID_FIRSTNAME_COLUMN = 0;
    private static final int LASTNAME_COLUMN = 1;

    /** Creates new form JTableJFrame */
    public JTableJFrame() {
        initComponents();

        // Listener per l'evento del cambio di selezione nella JTable.
        ListSelectionModel selectionModel = this.dataTable.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // Gestione Evento.
                // L'utente ha selezionato una nuova item della JTable.
                // Dalla documentazione di Java:
                // Returns whether or not this is one in a series of multiple
                // events, where changes are still being made.
                // See the documentation for
                //   ListSelectionModel.setValueIsAdjusting(boolean)
                // for more details on how this is used.
                // Returns: true if this is one in a series of multiple events,
                //          where changes are still being made.
                if (e.getValueIsAdjusting()) return;

                updateGUI();

                // Ottieni l'indice della row selezionata nella JTable (-1 se
                // nessuna selezione è attiva).
                int selRow = dataTable.getSelectedRow();
                if (selRow < 0) return;

                // Ottieni il DefaultTableModel della JTable.
                DefaultTableModel dtm = (DefaultTableModel) dataTable.getModel();

                // Una selezione è attiva, copia i dati della row selezionata
                // nei JTextFiels.
                // I campi id e firstName si trovano nell'oggetto IdFirstNameData
                // memorizzato nella cella della prima colonna.
                IdFirstNameData idFirst = (IdFirstNameData) dtm.getValueAt(selRow,
                                                                           JTableJFrame.ID_FIRSTNAME_COLUMN);
                idTextField.setText(idFirst.getId() + "");
                firstTextField.setText(idFirst.getFirstName());

                // La stringa del lastName è memorizzata (come String) nella
                // seconda colonna.
                lastTextField.setText((String) dtm.getValueAt(selRow,
                                                              JTableJFrame.LASTNAME_COLUMN));
            }
        });

        this.updateGUI();
    }

    private void updateGUI() {
        int id = -1;
        try {
            id = Integer.parseInt(this.idTextField.getText());
        } catch (NumberFormatException ex) { }

        boolean bDataOk = id > 0 && !this.firstTextField.getText().isBlank() &&
                                    !this.lastTextField.getText().isBlank();
        int selRow = this.dataTable.getSelectedRow();

        this.insertButton.setEnabled(bDataOk);
        this.deleteButton.setEnabled(selRow >= 0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataScrollPane = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        insertButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        firstLabel = new javax.swing.JLabel();
        firstTextField = new javax.swing.JTextField();
        lastLabel = new javax.swing.JLabel();
        lastTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JTable double data column");
        setMinimumSize(new java.awt.Dimension(448, 300));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FirstName", "LastName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataScrollPane.setViewportView(dataTable);

        insertButton.setText("Insert");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        idLabel.setText("ID:");

        idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataTextFieldsKeyReleased(evt);
            }
        });

        firstLabel.setText("First:");

        firstTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataTextFieldsKeyReleased(evt);
            }
        });

        lastLabel.setText("Last:");

        lastTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataTextFieldsKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(insertButton)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(firstLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lastLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertButton)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel)
                    .addComponent(firstLabel)
                    .addComponent(lastLabel)
                    .addComponent(lastTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        int id = -1;
        try {
            id = Integer.parseInt(this.idTextField.getText());
        } catch (NumberFormatException ex) { }
        String firstName = this.firstTextField.getText().trim();
        String lastName = this.lastTextField.getText().trim();

        if (id <= 0 || firstName.isBlank() || lastName.isBlank()) return;

        Object[] rowData = {
            // Memorizza id e firstName nella cella della prima colonna.
            new IdFirstNameData(id, firstName),
            lastName  // Memorizza il lastName nella cella della seconda colonna.
        };

        DefaultTableModel dtm = (DefaultTableModel) this.dataTable.getModel();

        // Inserisci una nuova row con i dati dei JTextField.
        dtm.addRow(rowData);
    }//GEN-LAST:event_insertButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selRow = this.dataTable.getSelectedRow();
        if (selRow < 0) return;

        // Elimina la row selezionata nella JTable.
        DefaultTableModel dtm = (DefaultTableModel) this.dataTable.getModel();
        dtm.removeRow(selRow);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void dataTextFieldsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataTextFieldsKeyReleased
        this.updateGUI();
    }//GEN-LAST:event_dataTextFieldsKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTableJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JTableJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane dataScrollPane;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JTextField firstTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel lastLabel;
    private javax.swing.JTextField lastTextField;
    // End of variables declaration//GEN-END:variables
}
