package TEST;

import java.awt.event.WindowEvent;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 * Database Negozio
 *
 * @date 03.12.2022
 * @author Marko Mirkovic
 */
public class ShopDBFrame extends javax.swing.JFrame {

    private static final int NOME_TABLE_COLUMN = 0;
    private static final int FORNITORE_TABLE_COLUMN = 1;
    private static final int QUANTITA_TABLE_COLUMN = 2;
    private static final int PREZZO_TABLE_COLUMN = 3;

    /**
     * Creates new form NegozioTable
     */
    private Connection conn;

    /**
     * Creates new form PersonDBFrame
     */
    public ShopDBFrame() {
        initComponents();

        // Listener per l'evento del cambio di selezione nella JTable.
        ListSelectionModel selectionModel = this.shopDataTable.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // L'utente ha selezionato una nuova item della JTable.
                // Dalla documentazione di Java:
                // Returns whether or not this is one in a series of multiple
                // events, where changes are still being made.
                // See the documentation for
                //   ListSelectionModel.setValueIsAdjusting(boolean)
                // for more details on how this is used.
                // Returns: true if this is one in a series of multiple events,
                //          where changes are still being made.
                if (e.getValueIsAdjusting()) {
                    return;
                }

                // Aggiorna lo stato della GUI.
                updateGUI();

                // Ottieni l'indice della row selezionata nella JTable (-1 se
                // nessuna selezione è attiva).
                int selRow = shopDataTable.getSelectedRow();
                if (selRow < 0) {
                    return;
                }

                // Ottieni il DefaultTableModel della JTable.
                // Nota: a differenza delle ultime 3 colonne (che contengono
                //       direttamente le stringhe di 'lastname', 'email' e
                //       'address'), la prima colonna (firstname) contiene un
                //       oggetto di tipo IdFirstnameItem, questo include la
                //       stringa per il 'firstname' e l'id della corrispondente
                //       row nel DB (la PK).
                //       L'id deve essere memorizzato (serve per le queries), ma
                //       non visualizzato (PK surrogata), vedi metodo toString()
                //       della classe IdFirstnameItem che, dei due dati, mostra
                //       appunto solo il 'firstname'.
                DefaultTableModel dtm = (DefaultTableModel) shopDataTable.getModel();

                // Una selezione è attiva nella JTable, copia i dati della row
                // selezionata nei relativi JTextFiels.
                IdNameItem idNome = (IdNameItem) dtm.getValueAt(selRow,
                        ShopDBFrame.NOME_TABLE_COLUMN);

                // Il 'firstname' è estratto dall'oggetto firstnameItem, gli
                // altri dati sono estratti direttamente dalle celle come stringhe.
                nomeTextField.setText(idNome.getName());
                fornitoreTextField.setText((String) dtm.getValueAt(selRow, ShopDBFrame.FORNITORE_TABLE_COLUMN));
                quantitaTextField.setText((String) dtm.getValueAt(selRow, ShopDBFrame.QUANTITA_TABLE_COLUMN));
                prezzoTextField.setText((String) dtm.getValueAt(selRow, ShopDBFrame.PREZZO_TABLE_COLUMN));
            }
        });

        // Crea o apri il database.
        this.createOrOpenDB();

        // Popola la JTable.
        this.refreshTableContent();

        // Inizializza lo stato della GUI.
        this.updateGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        shopTableScrollPane = new javax.swing.JScrollPane();
        shopDataTable = new javax.swing.JTable();
        nomeJLabel = new javax.swing.JLabel();
        quantitajLabel = new javax.swing.JLabel();
        prezzoJLabel = new javax.swing.JLabel();
        fornitoreJLabel4 = new javax.swing.JLabel();
        nomeTextField = new java.awt.TextField();
        fornitoreTextField = new java.awt.TextField();
        quantitaTextField = new java.awt.TextField();
        prezzoTextField = new java.awt.TextField();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ascRadioButton = new javax.swing.JRadioButton();
        descRadioButton = new javax.swing.JRadioButton();
        orderComboBox = new javax.swing.JComboBox<>();
        oderButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        shopTableScrollPane.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                shopTableScrollPaneKeyReleased(evt);
            }
        });

        shopDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Nome", "Fornitore", "Quantità", "Prezzo"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        shopDataTable.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                shopDataTableKeyReleased(evt);
            }
        });
        shopTableScrollPane.setViewportView(shopDataTable);

        nomeJLabel.setText("Nome");

        quantitajLabel.setText("Quantita");

        prezzoJLabel.setText("Prezzo");

        fornitoreJLabel4.setText("Fornitore");

        nomeTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                nomeTextFieldKeyReleased(evt);
            }
        });

        insertButton.setText("Insert");
        insertButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Order by:");

        buttonGroup1.add(ascRadioButton);
        ascRadioButton.setText("ASC");
        ascRadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ascRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(descRadioButton);
        descRadioButton.setText("DESC");
        descRadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                descRadioButtonActionPerformed(evt);
            }
        });

        orderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nome", "fornitore", "quantita", "prezzo" }));
        orderComboBox.setName(""); // NOI18N

        oderButton.setText("Order");
        oderButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                oderButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(shopTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nomeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quantitajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(refreshButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(quantitaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fornitoreJLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prezzoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fornitoreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(prezzoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ascRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(descRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(oderButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateButton)
                                .addGap(18, 18, 18)
                                .addComponent(insertButton)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shopTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fornitoreJLabel4)
                    .addComponent(nomeJLabel)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fornitoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(quantitajLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(prezzoJLabel))
                            .addComponent(quantitaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prezzoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insertButton)
                            .addComponent(updateButton)
                            .addComponent(deleteButton)
                            .addComponent(refreshButton))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ascRadioButton)
                            .addComponent(descRadioButton)
                            .addComponent(oderButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_insertButtonActionPerformed
    {//GEN-HEADEREND:event_insertButtonActionPerformed
        // TODO add your handling code here:
        // Inserisci una nuova row nel database.
        String sql = "INSERT INTO article (nome, fornitore, quantita, prezzo)"
                + " VALUES(?, ?, ?, ?)";
        try ( PreparedStatement pstmt = this.conn.prepareStatement(sql)) {
            // Sostituisci i quattro place-holder con i valori stringa dei
            // relativi JTextField.
            pstmt.setString(1, this.nomeTextField.getText());
            pstmt.setString(2, this.fornitoreTextField.getText());
            pstmt.setString(3, this.quantitaTextField.getText());
            pstmt.setString(4, this.prezzoTextField.getText());

            // Esegui la query di INSERT.
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Article List",
                    JOptionPane.ERROR_MESSAGE);
        }

        // Aggiorna il contenuto della JTable (con i nuovi dati del DB).
        this.refreshTableContent();
    }//GEN-LAST:event_insertButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_updateButtonActionPerformed
    {//GEN-HEADEREND:event_updateButtonActionPerformed
        // TODO add your handling code here:
        // Ottieni l'id (PK) della row nel database, questo è incapsulato
        // nell'oggetto IdFirstnameItem della prima colonna della row selezionata
        // nella JTable (-1 se nessuna selezione è attiva).
        // Id della row selezionata nella JTable.
        int selRow = this.shopDataTable.getSelectedRow();
        if (selRow < 0) {
            return;
        }
        
        
        // Ritorna l'oggetto IdNameItem (nella prima colonna).
        DefaultTableModel dtm = (DefaultTableModel) this.shopDataTable.getModel();
        IdNameItem idItem = (IdNameItem) dtm.getValueAt(selRow,
                ShopDBFrame.NOME_TABLE_COLUMN);

        // Modifica la row del DB (identificata dalla PK) corrispondente alla
        // row attualmente selezionata nella JTable.
        String sql = "UPDATE article SET nome = ?, fornitore = ?,"
                + " quantita = ?, prezzo = ?"
                + " WHERE id = ?";
        try ( PreparedStatement pstmt = this.conn.prepareStatement(sql)) {
            // Modifica 'nome', 'fornitore', 'quantita' e 'prezzo' (nel
            // database) con i valori stringa dei relativi JTextField.
            pstmt.setString(1, this.nomeTextField.getText());
            pstmt.setString(2, this.fornitoreTextField.getText());
            pstmt.setString(3, this.quantitaTextField.getText());
            pstmt.setString(4, this.prezzoTextField.getText());
            pstmt.setInt(5, idItem.getId());  // PK per la clusola WHERE.

            // Esegui la query di UPDATE.
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Article List",
                    JOptionPane.ERROR_MESSAGE);
        }

        // Aggiorna il contenuto della JTable (con i nuovi dati del DB).
        this.refreshTableContent();
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteButtonActionPerformed
    {//GEN-HEADEREND:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        
        // Ottieni l'id (PK) della row nel database, questo è incapsulato
        // nell'oggetto IdNameItem della prima colonna della row selezionata
        // nella JTable (-1 se nessuna selezione è attiva).
        // Id della row selezionata nella JTable.
        int selRow = this.shopDataTable.getSelectedRow();
        if (selRow < 0) {
            return;
        }

        // Ritorna l'oggetto IdFirstnameItem (nella prima colonna).
        DefaultTableModel dtm = (DefaultTableModel) this.shopDataTable.getModel();
        IdNameItem idItem = (IdNameItem) dtm.getValueAt(selRow,
                ShopDBFrame.NOME_TABLE_COLUMN);

        // Elimina una row del DB (identificata dalla PK) corrispondente alla
        // row attualmente selezionata nella JTable.
        String sql = "DELETE FROM article WHERE id = ?";
        try ( PreparedStatement pstmt = this.conn.prepareStatement(sql)) {
            // Imposta la condizione della clausola WHERE con il valore dell'id
            // incapsulato nell'oggetto IdFirstnameItem.
            pstmt.setInt(1, idItem.getId());  // PK per la clusola WHERE.

            // Esegui la query DELETE.
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Article List",
                    JOptionPane.ERROR_MESSAGE);
        }

        // Aggiorna il contenuto della JTable (con i nuovi dati del DB).
        this.refreshTableContent();
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void ascRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ascRadioButtonActionPerformed
    {//GEN-HEADEREND:event_ascRadioButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ascRadioButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_refreshButtonActionPerformed
    {//GEN-HEADEREND:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        // Aggiorna il contenuto della JTable con il contenuto del DB.
        this.refreshTableContent();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void descRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_descRadioButtonActionPerformed
    {//GEN-HEADEREND:event_descRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descRadioButtonActionPerformed

    private void oderButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_oderButtonActionPerformed
    {//GEN-HEADEREND:event_oderButtonActionPerformed
        // TODO add your handling code here:
        // Order by.
         // Ottieni il DefaultTableModel della JTable ed elimina tutte le row
        // della JTable (verranno sostituite dai nuovi dati nel DB).
        DefaultTableModel dtm = (DefaultTableModel) this.shopDataTable.getModel();
        dtm.setRowCount(0);

        try ( Statement stmt = this.conn.createStatement()) {
            // Esegui la SELECT e inserisci le row del DB nella JTable.
            String comboBox = this.orderComboBox.getSelectedItem().toString();
            System.out.println(comboBox);
            String query = "SELECT * FROM article ORDER BY " + comboBox + " ";
            query += (this.ascRadioButton.isSelected()) ? "ASC" : "DESC";
            System.out.println(query);
            try ( ResultSet rs = stmt.executeQuery(query)) {
                // Itera il resultSet.
                while (rs.next()) {
                    // Imposta l'array di Object con i dati della row da inserire.
                    // Un elemento Object può essere impostato direttamente con
                    // qualsiasi tipo di dato, questa operazione si chiama "boxing".
                    // L
                    Object[] rowData = {
                        new IdNameItem(rs.getInt("id"),
                        rs.getString("nome")),
                        rs.getString("fornitore"),
                        rs.getInt("quantita"),
                        rs.getInt("prezzo")
                    };

                    // Inserisci la nuova row.
                    dtm.addRow(rowData);
                }
            }

            // Aggiorna lo stato della GUI, dato che la JTable è stata svuotata
            // e poi ripopolata, una sua eventuale row-selection è andata persa.
            this.updateGUI();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Article List",
                    JOptionPane.ERROR_MESSAGE);
        }
                                         
    }//GEN-LAST:event_oderButtonActionPerformed

    private void nomeTextFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nomeTextFieldKeyReleased
    {//GEN-HEADEREND:event_nomeTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldKeyReleased

    private void shopTableScrollPaneKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_shopTableScrollPaneKeyReleased
    {//GEN-HEADEREND:event_shopTableScrollPaneKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_shopTableScrollPaneKeyReleased

    private void shopDataTableKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_shopDataTableKeyReleased
    {//GEN-HEADEREND:event_shopDataTableKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_shopDataTableKeyReleased

     
    
    //----------- inizio metodi
    
    private void refreshTableContent() {
        // Ottieni il DefaultTableModel della JTable ed elimina tutte le row
        // della JTable (verranno sostituite dai nuovi dati nel DB).
        DefaultTableModel dtm = (DefaultTableModel) this.shopDataTable.getModel();
        dtm.setRowCount(0);

        try ( Statement stmt = this.conn.createStatement()) {
            // Esegui la SELECT e inserisci le row del DB nella JTable.
            String sql = "SELECT * FROM article ORDER BY nome, fornitore";
            try ( ResultSet rs = stmt.executeQuery(sql)) {
                // Itera il resultSet.
                while (rs.next()) {
                    // Imposta l'array di Object con i dati della row da inserire.
                    // Un elemento Object può essere impostato direttamente con
                    // qualsiasi tipo di dato, questa operazione si chiama "boxing".
                    // L
                    Object[] rowData = {
                        new IdNameItem(rs.getInt("id"),
                        rs.getString("nome")),
                        rs.getString("fornitore"),
                        rs.getInt("quantita"),
                        rs.getInt("prezzo")
                    };

                    // Inserisci la nuova row.
                    dtm.addRow(rowData);
                }
            }

            // Aggiorna lo stato della GUI, dato che la JTable è stata svuotata
            // e poi ripopolata, una sua eventuale row-selection è andata persa.
            this.updateGUI();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Article List",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

//    private void orderBy() {
//        // Ottieni il DefaultTableModel della JTable ed elimina tutte le row
//        // della JTable (verranno sostituite dai nuovi dati nel DB).
//        DefaultTableModel dtm = (DefaultTableModel) this.personDataTable.getModel();
//        dtm.setRowCount(0);
//
//        try ( Statement stmt = this.conn.createStatement()) {
//            // Esegui la SELECT e inserisci le row del DB nella JTable.
//            String comboBox = this.orderComboBox.getSelectedItem().toString();
//            System.out.println(comboBox);
//            String query = "SELECT * FROM article ORDER BY " + comboBox + " ";
//            query += (this.ascRadioButton.isSelected()) ? "ASC" : "DESC";
//            System.out.println(query);
//            try ( ResultSet rs = stmt.executeQuery(query)) {
//                // Itera il resultSet.
//                while (rs.next()) {
//                    // Imposta l'array di Object con i dati della row da inserire.
//                    // Un elemento Object può essere impostato direttamente con
//                    // qualsiasi tipo di dato, questa operazione si chiama "boxing".
//                    // L
//                    Object[] rowData = {
//                        new IdFirstnameItem(rs.getInt("id"),
//                        rs.getString("firstname")),
//                        rs.getString("lastname"),
//                        rs.getString("email"),
//                        rs.getString("address")
//                    };
//
//                    // Inserisci la nuova row.
//                    dtm.addRow(rowData);
//                }
//            }
//
//            // Aggiorna lo stato della GUI, dato che la JTable è stata svuotata
//            // e poi ripopolata, una sua eventuale row-selection è andata persa.
//            this.updateGUI();
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, ex.getMessage(),
//                    "article List",
//                    JOptionPane.ERROR_MESSAGE);
//        }
//    }

    private void updateGUI() {
        // Determina lo stato dei 3 JTextField e se la JTable ha una selezione.
        boolean isValidData = !this.nomeTextField.getText().isBlank()
                && !this.fornitoreTextField.getText().isBlank()
                && !this.quantitaTextField.getText().isBlank()
                && !this.prezzoTextField.getText().isBlank();
        boolean hasSelection = this.shopDataTable.getSelectedRow() >= 0;

        // Aggiorna lo stato di 'enabled' dei button.
        this.insertButton.setEnabled(isValidData);
        this.updateButton.setEnabled(isValidData && hasSelection);
        this.deleteButton.setEnabled(hasSelection);
    }

    private void createOrOpenDB() {
        try {
            Class.forName("org.sqlite.JDBC");

            // Apre la connessione con il database, se il db non esiste, viene creato.
            this.conn = DriverManager.getConnection("jdbc:sqlite:Shop.db");//Shop --------------

            // Crea la tabella 'person' se non esiste ancora.
            try ( Statement stmt = this.conn.createStatement()) {
                String sql = "CREATE TABLE IF NOT EXISTS article ("
                        + " id INTEGER NOT NULL,"
                        + " nome TEXT NOT NULL,"
                        + " fornitore TEXT NOT NULL,"
                        + " quantita INTEGER NOT NULL,"
                        + " prezzo  DOUBLE NOT NULL,"
                        + " PRIMARY KEY (id))";
                stmt.executeUpdate(sql);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            String err = ex.getMessage().trim();
            if (ex instanceof ClassNotFoundException) {
                err = "Class '" + err + "' not found.";
            }

            JOptionPane.showMessageDialog(null,
                    err + "\n\nTerminating the application!",
                    "Article List",
                    JOptionPane.ERROR_MESSAGE);

            // Termina l'applicazione, errore non rimediabile.
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }
    
    
    //----------- fine metodi
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ShopDBFrame().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ascRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JRadioButton descRadioButton;
    private javax.swing.JLabel fornitoreJLabel4;
    private java.awt.TextField fornitoreTextField;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomeJLabel;
    private java.awt.TextField nomeTextField;
    private javax.swing.JButton oderButton;
    private javax.swing.JComboBox<String> orderComboBox;
    private javax.swing.JLabel prezzoJLabel;
    private java.awt.TextField prezzoTextField;
    private java.awt.TextField quantitaTextField;
    private javax.swing.JLabel quantitajLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable shopDataTable;
    private javax.swing.JScrollPane shopTableScrollPane;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

}
