
package todo;


import java.awt.event.WindowEvent;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 * ToDo Manager - Test SJAV
 * @author Marko Mirkovic
 * @version 05.12.2022
 */
public class ToDoDBFrame extends javax.swing.JFrame {

    private static final int TITLE_TABLE_COLUMN = 0;
    private static final int DESCRIPTION_TABLE_COLUMN = 1;
    private static final int DEADLINE_TABLE_COLUMN = 2;
    
    
    /**
     * Creates new form todo table
     */
    private Connection conn;
    
    
    /**
     * Creates new form ToDoManagerFrame
     */
    public ToDoDBFrame() {
        initComponents();
    
        ListSelectionModel selectionModel = this.toDoTable.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // L'utente ha selezionato una nuova item della JTable.
                // Returns: true if this is one in a series of multiple events,
                //          where changes are still being made.
                if (e.getValueIsAdjusting()) {
                    return;
                }

                // Aggiorna lo stato della GUI.
                updateGUI();

                // Ottieni l'indice della row selezionata nella JTable (-1 se
                // nessuna selezione è attiva).
                int selRow = toDoTable.getSelectedRow();
                if (selRow < 0) {
                    return;
                }

                // Ottieni il DefaultTableModel della JTable.
                DefaultTableModel dtm = (DefaultTableModel) toDoTable.getModel();

                // Una selezione è attiva nella JTable, copia i dati della row
                // selezionata nei relativi JTextFiels.

                // Il 'firstname' è estratto dall'oggetto firstnameItem, gli
                // altri dati sono estratti direttamente dalle celle come stringhe.
                
                titleTextField.setText((String) dtm.getValueAt(selRow, ToDoDBFrame.TITLE_TABLE_COLUMN));
                descriptionTextField.setText((String) dtm.getValueAt(selRow, ToDoDBFrame.DESCRIPTION_TABLE_COLUMN));
                deadlineTextField.setText((String) dtm.getValueAt(selRow, ToDoDBFrame.DEADLINE_TABLE_COLUMN));
            
                // Una selezione è attiva, copia i dati della row selezionata
                // nei JTextFiels.
//                int id = (int) dtm.getValueAt(selRow,
//                                              ToDoDBFrame.TITLE_TABLE_COLUMN);
//                titleTextField.setText(id + "");
//                
//                descriptionTextField.setText((String) dtm.getValueAt(selRow,
//                                           ToDoDBFrame.DESCRIPTION_TABLE_COLUMN));
//                
//                deadlineTextField.setText((String) dtm.getValueAt(selRow,
//                                          ToDoDBFrame.DEADLINE_TABLE_COLUMN));
                
                // Aggiorna lo stato di enabled/disabled dei button della GUI.
                updateGUI();
            }
        });

        // Crea o apri il database.
        this.createOrOpenDB();

        // Popola la JTable.
        this.refreshTableContent();

        // Inizializza lo stato della GUI.
        this.updateGUI();
    
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toDoScrollPane = new javax.swing.JScrollPane();
        toDoTable = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        deadLineLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        descriptionTextField = new javax.swing.JTextField();
        deadlineTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        deleteAllButton = new javax.swing.JButton();
        sortByLabel = new javax.swing.JLabel();
        sortByComboBox = new javax.swing.JComboBox<>();
        reloadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ToDo Manager");

        toDoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Description", "Deadline"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        toDoTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        toDoScrollPane.setViewportView(toDoTable);

        titleLabel.setText("Title:");

        descriptionLabel.setText("Description:");

        deadLineLabel.setText("Deadline:");

        deadlineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadlineTextFieldActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        deleteAllButton.setText("Delete All");
        deleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllButtonActionPerformed(evt);
            }
        });

        sortByLabel.setText("Sort by:");

        sortByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title ▼", "Description ▼", "Deadline ▼" }));

        reloadButton.setText("Reload");
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(descriptionLabel)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleLabel)
                                    .addComponent(deadLineLabel))
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deadlineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(titleTextField)
                            .addComponent(descriptionTextField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteAllButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(toDoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sortByLabel)
                    .addComponent(reloadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sortByComboBox, 0, 108, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sortByLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reloadButton))
                    .addComponent(toDoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionLabel)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deadlineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deadLineLabel)
                    .addComponent(deleteAllButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deadlineTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadlineTextFieldActionPerformed
                
    }//GEN-LAST:event_deadlineTextFieldActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selRow = this.toDoTable.getSelectedRow();
        if (selRow < 0) {
            return;
        }

        // Ritorna l'oggetto TitleItem (nella prima colonna).
        DefaultTableModel dtm = (DefaultTableModel) this.toDoTable.getModel();
        

        // Elimina una row del DB (identificata dalla PK) corrispondente alla
        // row attualmente selezionata nella JTable.
        String sql = "DELETE FROM todo WHERE id = ?";
        try ( PreparedStatement pstmt = this.conn.prepareStatement(sql)) {
            // Imposta la condizione della clausola WHERE con il valore dell'id
            // incapsulato nell'oggetto IdFirstnameItem.
            //pstmt.setInt(1, idItem.getId());  // PK per la clusola WHERE.
            //pstmt.setString(1, title.getText());  // PK per la clusola WHERE.
            pstmt.setString(1, this.titleTextField.getText());

            // Esegui la query DELETE.
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "Article List",
                    JOptionPane.ERROR_MESSAGE);
        }

        // Aggiorna il contenuto della JTable (con i nuovi dati del DB).
        this.refreshTableContent();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // Add
        String sql = "INSERT INTO todo (title, description, deadline)"
                + " VALUES(?, ?, ?)";
        try ( PreparedStatement pstmt = this.conn.prepareStatement(sql)) {
            // Sostituisci i quattro place-holder con i valori stringa dei
            // relativi JTextField.
            pstmt.setString(1, this.titleTextField.getText());
            pstmt.setString(2, this.descriptionTextField.getText());
            pstmt.setString(3, this.deadlineTextField.getText());

            // Esegui la query di INSERT.
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "ToDo List",
                    JOptionPane.ERROR_MESSAGE);
        }

        // Aggiorna il contenuto della JTable (con i nuovi dati del DB).
        this.refreshTableContent();
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteAllButtonActionPerformed

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        this.refreshTableContent();
    }//GEN-LAST:event_reloadButtonActionPerformed

    
    //----------- inizio metodi
    
     /**
      * refreshTableContent metodo void
      * 
      */
     private void refreshTableContent() {
        // Ottieni il DefaultTableModel della JTable ed elimina tutte le row
        // della JTable (verranno sostituite dai nuovi dati nel DB).
        DefaultTableModel dtm = (DefaultTableModel) this.toDoTable.getModel();
        dtm.setRowCount(0);

        try ( Statement stmt = this.conn.createStatement()) {
            // Esegui la SELECT e inserisci le row del DB nella JTable.
            String sql = "SELECT * FROM todo ORDER BY title, description";
            try ( ResultSet rs = stmt.executeQuery(sql)) {
                // Itera il resultSet.
                while (rs.next()) {
                    // Imposta l'array di Object con i dati della row da inserire.
                    // Un elemento Object può essere impostato direttamente con
                    // qualsiasi tipo di dato, questa operazione si chiama "boxing".
                    // L
                    Object[] rowData = {
                        //new IdNameItem(rs.getInt("id"),
                        rs.getString("title"),
                        rs.getString("description"),
                        rs.getString("deadline")
                    };

                    // Inserisci la nuova row.
                    dtm.addRow(rowData);
                }
            }

            // Aggiorna lo stato della GUI, dato che la JTable è stata svuotata
            // e poi ripopolata, una sua eventuale row-selection è andata persa.
            this.updateGUI();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                    "ToDo Manager List",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
   
    /**
     * updateGUI metodo void
     */ 
    private void updateGUI() {
        // Determina lo stato dei 3 JTextField e se la JTable ha una selezione.
        boolean isValidData = !this.titleTextField.getText().isBlank()
                && !this.descriptionTextField.getText().isBlank()
                && !this.deadlineTextField.getText().isBlank();
        boolean hasSelection = this.toDoTable.getSelectedRow() >= 0;

        // Aggiorna lo stato di 'enabled' dei button.
        this.addButton.setEnabled(isValidData);
        this.deleteButton.setEnabled(isValidData && hasSelection);
        this.deleteAllButton.setEnabled(isValidData && hasSelection);
        this.reloadButton.setEnabled(isValidData);
    }

    
    /**
     * createOrOpenDB void metodo
     */
    private void createOrOpenDB() {
        try {
            System.out.println("x");
            Class.forName("org.sqlite.JDBC");
            System.out.println("xx");
            // Apre la connessione con il database, se il db non esiste, viene creato.
            this.conn = DriverManager.getConnection("jdbc:sqlite:ToDo.db");//working directory --------------
            //System.out.println(conn.getMetaData().getDriverName());
            // Crea la tabella 'person' se non esiste ancora.
            try ( Statement stmt = this.conn.createStatement()) {
                String sql = "CREATE TABLE IF NOT EXISTS todo ("
                        + " title TEXT NOT NULL,"
                        + " description TEXT NOT NULL,"
                        + " deadline INTEGER NOT NULL,"
                        + " PRIMARY KEY (title))";
                stmt.executeUpdate(sql);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            String err = ex.getMessage().trim();
            if (ex instanceof ClassNotFoundException) {
                err = "Class '" + err + "' not found.";
                //System.err.println( ex.getClass().getName() + ": " + ex.getMessage() );
                //System.exit(0);
            }

            JOptionPane.showMessageDialog(null,
                    err + "\n\nTerminating the application!",
                    "ToDo List",
                    JOptionPane.ERROR_MESSAGE);

            // Termina l'applicazione, errore non rimediabile.
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
        System.out.println("Opened database successfully");
    }
    
    
    //----------- fine metodi
    
    
    
    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToDoDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToDoDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToDoDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToDoDBFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        System.out.println("JDBC");
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new ToDoDBFrame().setVisible(true);
                
            } 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel deadLineLabel;
    private javax.swing.JTextField deadlineTextField;
    private javax.swing.JButton deleteAllButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JButton reloadButton;
    private javax.swing.JComboBox<String> sortByComboBox;
    private javax.swing.JLabel sortByLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JScrollPane toDoScrollPane;
    private javax.swing.JTable toDoTable;
    // End of variables declaration//GEN-END:variables
}
