/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package a2;

import java.awt.Color;

/**
 *
 * @author marko.mirkovic
 * @version 28 November 2022
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        placeholderTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        placeholderTextField.setForeground(new java.awt.Color(204, 204, 204));
        placeholderTextField.setText("Placeholder");
        placeholderTextField.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                placeholderTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                placeholderTextFieldFocusLost(evt);
            }
        });
        placeholderTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                placeholderTextFieldActionPerformed(evt);
            }
        });
        placeholderTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                placeholderTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(placeholderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(placeholderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placeholderTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_placeholderTextFieldActionPerformed
    {//GEN-HEADEREND:event_placeholderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeholderTextFieldActionPerformed

    private void placeholderTextFieldFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_placeholderTextFieldFocusGained
    {//GEN-HEADEREND:event_placeholderTextFieldFocusGained
        // TODO add your handling code here:
        Color clr = this.placeholderTextField.getForeground();
        if (clr == Color.BLACK) {
            if(this.placeholderTextField.getText().isBlank() ) {
                this.placeholderTextField.setText("Placeholder");
                this.placeholderTextField.setForeground(new Color(192, 192, 192));
            }
            else
            {
                this.placeholderTextField.setForeground(new Color(0, 0, 0));
            }
        }
        else 
        {
            
        }
    }//GEN-LAST:event_placeholderTextFieldFocusGained

    private void placeholderTextFieldFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_placeholderTextFieldFocusLost
    {//GEN-HEADEREND:event_placeholderTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_placeholderTextFieldFocusLost

    private void placeholderTextFieldKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_placeholderTextFieldKeyReleased
    {//GEN-HEADEREND:event_placeholderTextFieldKeyReleased
        // TODO add your handling code here:
        this.checkPlaceholder();
    }//GEN-LAST:event_placeholderTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //if ("Nimbus".equals(info.getName())) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField placeholderTextField;
    // End of variables declaration//GEN-END:variables

    private void checkPlaceholder()
    {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
