/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package aa;

/**
 *
 * @author marko.mirkovic
 * @version 28 November 2022
 */
public class NewJframe extends javax.swing.JFrame {

    /** Creates new form NewJframe */
    public NewJframe() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        OrderBy = new javax.swing.ButtonGroup();
        testButton = new javax.swing.JButton();
        ascRadioButton = new javax.swing.JRadioButton();
        descRadioButton = new javax.swing.JRadioButton();
        lastnameTextField = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        testButton.setText("Test");
        testButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                testButtonActionPerformed(evt);
            }
        });

        OrderBy.add(ascRadioButton);
        ascRadioButton.setSelected(true);
        ascRadioButton.setText("Asc");
        ascRadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ascRadioButtonActionPerformed(evt);
            }
        });

        OrderBy.add(descRadioButton);
        descRadioButton.setText("Desc");

        lastnameTextField.setToolTipText("Sono il toolTipText");

        lastnameLabel.setText("Lastname");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(testButton)
                        .addGap(18, 18, 18)
                        .addComponent(ascRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(descRadioButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lastnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastnameTextField)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testButton)
                    .addComponent(ascRadioButton)
                    .addComponent(descRadioButton))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameLabel))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ascRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ascRadioButtonActionPerformed
    {//GEN-HEADEREND:event_ascRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ascRadioButtonActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testButtonActionPerformed
    {//GEN-HEADEREND:event_testButtonActionPerformed
        // TODO add your handling code here:
        String lastname = this.lastnameTextField.getText();
        System.out.println(lastname);
        
        
        String query = "SELECT * FROM users WHERE lastname = ? ORDER BY lastname ";
        query += (this.ascRadioButton.isSelected()) ? "ASC" : "DESC";
        System.out.println(query);
        //String x = "abc \" def";
        
        //query = query.replaceAll("\\?", "'" + lastname);
    }//GEN-LAST:event_testButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //if ("Nimbus".equals(info.getName())) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup OrderBy;
    private javax.swing.JRadioButton ascRadioButton;
    private javax.swing.JRadioButton descRadioButton;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JButton testButton;
    // End of variables declaration//GEN-END:variables

}
