package jTableDemo;

import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neil Otupacca
 * @version 24 October 2021
 */
public class JTableDemoFrame extends javax.swing.JFrame {

    // Costanti per gli indice delle 3 colonne della JTable.
    private static final int ID_TABLE_COLUMN = 0;
    private static final int FIRSTNAME_TABLE_COLUMN = 1;
    private static final int LASTNAME_TABLE_COLUMN = 2;

    /** Creates new form NewJFrame */
    public JTableDemoFrame() {
        initComponents();

        // Listener per l'evento del cambio di selezione nella JTable.
        ListSelectionModel selectionModel = this.listTable.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // Gestione  Evento ///////////////////////////////////
                // L'utente ha selezionato una nuova item della JTable.
                // Dalla documentazione di Java:
                // Returns whether or not this is one in a series of multiple
                // events, where changes are still being made.
                // See the documentation for
                //   ListSelectionModel.setValueIsAdjusting(boolean)
                // for more details on how this is used.
                // Returns: true if this is one in a series of multiple events,
                //          where changes are still being made.
                if (e.getValueIsAdjusting()) return;

                // Ottieni l'indice della row selezionata nella JTable (-1 se
                // nessuna selezione è attiva).
                int selRow = listTable.getSelectedRow();
                if (selRow < 0) return;

                // Ottieni il DefaultTableModel della JTable.
                DefaultTableModel dtm = (DefaultTableModel) listTable.getModel();

                // Una selezione è attiva, copia i dati della row selezionata
                // nei JTextFiels.
                int id = (int) dtm.getValueAt(selRow,
                                              JTableDemoFrame.ID_TABLE_COLUMN);
                idTextField.setText(id + "");
                firstnameTextField.setText((String) dtm.getValueAt(selRow,
                                           JTableDemoFrame.FIRSTNAME_TABLE_COLUMN));
                lastnameTextField.setText((String) dtm.getValueAt(selRow,
                                          JTableDemoFrame.LASTNAME_TABLE_COLUMN));

                // Aggiorna lo stato di enabled/disabled dei button della GUI.
                updateGUI();
            }
        });

        // Aggiorna lo stato di enabled/disabled dei button della GUI.
        this.updateGUI();
    }

    // Metodo di utility privato.
    private void updateGUI() {
        // Ottieni l'indice della row selezionata nella JTable (-1 se nessuna
        // selezione è attiva) e il numero di rows corrente.
        int selRow = this.listTable.getSelectedRow();
        int rowsCount = this.listTable.getRowCount();

        // Determina se il contenuto di tutti i JTextField è valido.
        // Il valore dell'id deve essere un numero maggiore o uguale a zero.
        boolean isNumeric = false;
        try {
            int val = Integer.parseInt(this.idTextField.getText());
            if (val >= 0) isNumeric = true;
        } catch (NumberFormatException ex) { }

        // I valori dell'id, del firstname e del lastname devono essere validi.
        boolean isValidEntry = isNumeric &&
                               !this.firstnameTextField.getText().isBlank() &&
                               !this.lastnameTextField.getText().isBlank();

        // Abilita/disabilita i button della GUI in funzione dello stato della
        // JTable (selected item) e del contenuto dei JTextField.
        this.insertNewButton.setEnabled(isValidEntry);
        this.modifySelectedButton.setEnabled(selRow >= 0 && isValidEntry);
        this.deleteSelectedButton.setEnabled(selRow >= 0);
        this.deleteAllButton.setEnabled(rowsCount > 0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listScrollPane = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();
        insertNewButton = new javax.swing.JButton();
        modifySelectedButton = new javax.swing.JButton();
        deleteSelectedButton = new javax.swing.JButton();
        deleteAllButton = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        firstnameLabel = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        lastnameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JTable Demo");
        setMinimumSize(new java.awt.Dimension(406, 250));

        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Firstname", "Lastname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listScrollPane.setViewportView(listTable);

        insertNewButton.setText("Insert");
        insertNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertNewButtonActionPerformed(evt);
            }
        });

        modifySelectedButton.setText("Modify Selected");
        modifySelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifySelectedButtonActionPerformed(evt);
            }
        });

        deleteSelectedButton.setText("Delete Selected");
        deleteSelectedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectedButtonActionPerformed(evt);
            }
        });

        deleteAllButton.setText("Delete all");
        deleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllButtonActionPerformed(evt);
            }
        });

        idLabel.setText("Id:");

        idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldsChangedKeyReleased(evt);
            }
        });

        firstnameLabel.setText("Firstname:");

        firstnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldsChangedKeyReleased(evt);
            }
        });

        lastnameLabel.setText("Lastname:");

        lastnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldsChangedKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insertNewButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modifySelectedButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteSelectedButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteAllButton))
                    .addComponent(listScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertNewButton)
                    .addComponent(deleteAllButton)
                    .addComponent(deleteSelectedButton)
                    .addComponent(modifySelectedButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel)
                    .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameLabel)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameLabel))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertNewButtonActionPerformed
        // Gestione  Evento ///////////////////////
        // L'utente ha cliccato il button "Insert".

        // Ottieni il valore dell'id.
        int id = -1;
        try {
            id = Integer.parseInt(this.idTextField.getText());
        } catch (NumberFormatException ex) { }

        // L'id deve essere numerico e maggiore o uguale a 0.
        if (id < 0) return;

        // Imposta l'array di Object con i dati della row da inserire.
        // Un elemento Object può essere impostato direttamente con qualsiasi
        // tipo di dato, questa operazione si chiama "boxing".
        Object[] rowData = {
            id,
            this.firstnameTextField.getText(),
            this.lastnameTextField.getText()
        };

        // Ottieni il DefaultTableModel della JTable.
        DefaultTableModel dtm = (DefaultTableModel) this.listTable.getModel();

        // Inserisci una nuova row con i dati dei JTextField.
        dtm.addRow(rowData);
    }//GEN-LAST:event_insertNewButtonActionPerformed

    private void modifySelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifySelectedButtonActionPerformed
        // Gestione  Evento ////////////////////////////////
        // L'utente ha cliccato il button "Modify Selected".

        // Ottieni il valore dell'id.
        int id = -1;
        try {
            id = Integer.parseInt(this.idTextField.getText());
        } catch (NumberFormatException ex) { }

        // L'id deve essere numerico e maggiore o uguale a zero.
        if (id < 0) return;

        // Ottieni l'indice della row selezionata nella JTable (-1 se nessuna
        // selezione è attiva).
        int selRow = this.listTable.getSelectedRow();
        if (selRow < 0) return;

        // Modifica i valori delle colonne della row selezionata.
        DefaultTableModel dtm = (DefaultTableModel) this.listTable.getModel();
        dtm.setValueAt(id, selRow, JTableDemoFrame.ID_TABLE_COLUMN);
        dtm.setValueAt(this.firstnameTextField.getText(), selRow,
                       JTableDemoFrame.FIRSTNAME_TABLE_COLUMN);
        dtm.setValueAt(this.lastnameTextField.getText(), selRow,
                       JTableDemoFrame.LASTNAME_TABLE_COLUMN);
    }//GEN-LAST:event_modifySelectedButtonActionPerformed

    private void deleteSelectedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedButtonActionPerformed
        // Gestione  Evento ////////////////////////////////
        // L'utente ha cliccato il button "Delete Selected".

        // Ottieni l'indice della row selezionata nella JTable (-1 se nessuna
        // selezione è attiva).
        int selRow = this.listTable.getSelectedRow();
        if (selRow < 0) return;

        // Ottieni il DefaultTableModel della JTable ed elimina la row selezionata.
        DefaultTableModel dtm = (DefaultTableModel) this.listTable.getModel();
        dtm.removeRow(selRow);
    }//GEN-LAST:event_deleteSelectedButtonActionPerformed

    private void deleteAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllButtonActionPerformed
        // Gestione  Evento ///////////////////////////
        // L'utente ha cliccato il button "Delete All".

        // Ottieni il DefaultTableModel della JTable ed elimina tutte le row
        // della JTable.
        DefaultTableModel dtm = (DefaultTableModel) this.listTable.getModel();
        dtm.setRowCount(0);
    }//GEN-LAST:event_deleteAllButtonActionPerformed

    private void textFieldsChangedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldsChangedKeyReleased
        // Aggiorna lo stato di enabled/disabled dei button della GUI.
        this.updateGUI();
    }//GEN-LAST:event_textFieldsChangedKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTableDemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JTableDemoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteAllButton;
    private javax.swing.JButton deleteSelectedButton;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton insertNewButton;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JTable listTable;
    private javax.swing.JButton modifySelectedButton;
    // End of variables declaration//GEN-END:variables
}
