package persondbpersonremake;


import java.awt.event.WindowEvent;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
//import persondbpersonremake.ShopDBFrame.IdNameItem;

/**
 *
 * @author marko.mirkovic
 * @version 03 December 2022
 */
public class ShopTableFrame extends javax.swing.JFrame {
    
    // Costanti per gli indice delle 4 colonne della JTable.
    private static final int NOME_TABLE_COLUMN = 0;
    private static final int FORNITORE_TABLE_COLUMN = 1;
    private static final int QUANTITA_TABLE_COLUMN = 2;
    private static final int PREZZO_TABLE_COLUMN = 3;

    
    private Connection conn;
    
    
    /**
     * Creates new form PersonDBFrame
     */
    public ShopTableFrame() {
        initComponents();

        // Listener per l'evento del cambio di selezione nella JTable.
        ListSelectionModel selectionModel = this.shopDataTable.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // L'utente ha selezionato una nuova item della JTable.
                // Dalla documentazione di Java:
                // Returns whether or not this is one in a series of multiple
                // events, where changes are still being made.
                // See the documentation for
                //   ListSelectionModel.setValueIsAdjusting(boolean)
                // for more details on how this is used.
                // Returns: true if this is one in a series of multiple events,
                //          where changes are still being made.
                if (e.getValueIsAdjusting()) {
                    return;
                }

                // Aggiorna lo stato della GUI.
                updateGUI();

                // Ottieni l'indice della row selezionata nella JTable (-1 se
                // nessuna selezione è attiva).
                int selRow = shopDataTable.getSelectedRow();
                if (selRow < 0) {
                    return;
                }

                // Ottieni il DefaultTableModel della JTable.
                // Nota: a differenza delle ultime 3 colonne (che contengono
                //       direttamente le stringhe di 'lastname', 'email' e
                //       'address'), la prima colonna (firstname) contiene un
                //       oggetto di tipo IdFirstnameItem, questo include la
                //       stringa per il 'firstname' e l'id della corrispondente
                //       row nel DB (la PK).
                //       L'id deve essere memorizzato (serve per le queries), ma
                //       non visualizzato (PK surrogata), vedi metodo toString()
                //       della classe IdFirstnameItem che, dei due dati, mostra
                //       appunto solo il 'firstname'.
                DefaultTableModel dtm = (DefaultTableModel) shopDataTable.getModel();

                // Una selezione è attiva nella JTable, copia i dati della row
                // selezionata nei relativi JTextFiels.
                IdNameItem idName = (IdNameItem) dtm.getValueAt(selRow,
                        ShopDBFrame.NOME_TABLE_COLUMN);

                // Il 'firstname' è estratto dall'oggetto firstnameItem, gli
                // altri dati sono estratti direttamente dalle celle come stringhe.
                nameTextField.setText(firstnameItem.getName());
                fornitoreTextField.setText((String) dtm.getValueAt(selRow, PersonDBFrame.LASTNAME_TABLE_COLUMN));
                quantitaTextField.setText((String) dtm.getValueAt(selRow, PersonDBFrame.EMAIL_TABLE_COLUMN));
                prezzoTextField.setText((String) dtm.getValueAt(selRow, PersonDBFrame.ADDRESS_TABLE_COLUMN));
            }
        });

        // Crea o apri il database.
        this.createOrOpenDB();

        // Popola la JTable.
        this.refreshTableContent();

        // Inizializza lo stato della GUI.
        this.updateGUI();
    }

    
    
    /** Creates new form ShopTable */
    public ShopTableFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        shopDataTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        shopDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Nome", "Fornitore", "Quantita", "Prezzo"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(shopDataTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //if ("Nimbus".equals(info.getName())) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopTableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopTableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopTableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopTableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopTableFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable shopDataTable;
    // End of variables declaration//GEN-END:variables

}
